---
- name: Install the nop commerce application
  hosts: webserver
  become: yes
  tasks:
    - name: Download the debian file
      get_url:
        url: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
        dest: /tmp/packages-microsoft-prod.deb
    - name: install debian package
      apt:
        deb: /tmp/packages-microsoft-prod.deb
    - name: install the .net core run times
      apt:
        name: "{{ item }}"
        update_cache: yes
        state: present
      with_items:
        - apt-transport-https
        - aspnetcore-runtime-3.1
    - name: install nginx
      apt:
        name: nginx
        state: present
      notify:
        - start nginx
  handlers:
    - name: start nginx
      systemd:
        name: nginx
        state: started
