---
- name: Install the nop commerce application
  hosts: webserver
  become: yes
  tasks:
    - name: Download the debian file
      get_url:
        url: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
        dest: /tmp/packages-microsoft-prod.deb
    - name: install debian package
      apt:
        deb: /tmp/packages-microsoft-prod.deb
    - name: install the .net core run times
      apt:
        name: "{{ item }}"
        update_cache: yes
        state: present
      with_items:
        - apt-transport-https
        - aspnetcore-runtime-3.1
    - name: install nginx
      apt:
        name: nginx
        state: present
      notify:
        - start nginx
    - name: create a directory nopcemmerce
      file:
        path: /var/www/nopCommerce440
        state: directory
    - name: Download the nopcemmerce
      get_url:
        url: https://github.com/nopSolutions/nopCommerce/releases/download/release-4.40.4/nopCommerce_4.40.4_NoSource_linux_x64.zip
        dest: tmp/nopCommerce_4.40.4_NoSource_linux_x64.zip
    - name: install unzip
      apt:
        name: unzip
        state: present
    - name: unzip the zip
      unarchive:
        src: tmp/nopCommerce_4.40.4_NoSource_linux_x64.zip
        dest: /var/www/nopCommerce440/
  handlers:
    - name: start nginx
      systemd:
        name: nginx
        state: started
