---
- name: Deploy springboot application
  hosts: appserver
  become: yes
  vars:
    java_package: openjdk-11-jdk
    app_dir: /usr/share/spring-petclinic
    app_url_download: https://referenceapplicationskhaja.s3-us-west-2.amazonaws.com/spring-petclinic-2.4.2.jar
    app_path: /usr/share/spring-petclinic/spring-petclinic-2.4.2.jar
    app_user: spcuser

  tasks:
    - name: Fail the execution when the distribution is not ubuntu and RedHat
      fail:
        msg: this play-book will work on centos and ubuntu
      when:
        - ansible_facts['distribution'] != "Ubuntu"
        - ansible_facts['distribution'] != "RedHat"
    - name: install java
      apt:
        name: "{{ java_package }}"
        state: present
        update_cache: yes
    - name: create a spc directory
      file:
        path: "{{ app_dir }}"
        state: directory
      notify:
        - debug message for directory creation
    - name: download the spc.jar file
      get_url:
        url: "{{ app_url_download }}"
        dest: "{{ app_path }}"
    - name: create spc user
      user:
        name: "{{ app_user }}"
        state: present
      notify:
        - change ownership of jar file
    - name: copy the service file
      copy:
        src: template/spc.service.j2
        dest: /etc/systemd/system/spc.service
        remote_src: yes
    - name: enable and restart spc
      systemd:
        name: spc.service
        enabled: yes
        state: started
  handlers:
    - name: change ownership of jar file
      file:
        path: "{{ app_path }}"
        owner: "{{ app_user }}"
        mode: 500
        state: file
    - name: debug message for directory creation
      debug:
        msg: " direcotry created at {{ app_dir }} "
